version: '3'
volumes:
  shared:
    driver: local
services:
  redmatch:
    image: aehrc/redmatch:@project.version@
    container_name: redmatch
    depends_on:
      - keycloak
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - 8080:8080
    volumes:
      - shared:/usr/share/redmatch
  keycloak:
      build: keycloak
      container_name: keycloak
      environment:
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: secret
        KEYCLOAK_IMPORT: tmp/realm-export.json
      ports:
        - 10001:8080
        - 9990:9990
