name: Build, Test and Deploy

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up jdk
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: cache maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: install FHIR R4
        run: |
          mkdir -p ~/.fhir/packages/hl7.fhir.r4.core#4.0.1
          npm init --yes
          npm --registry https://packages.simplifier.net install hl7.fhir.r4.core@4.0.1
          mv node_modules/hl7.fhir.r4.core ~/.fhir/packages/hl7.fhir.r4.core#4.0.1/package

      - name: build and test with maven
        run: mvn -B verify --file pom.xml

      - name: vsce setup
        run: npm install -g vsce@"^1.0.0"

      - name: vsce package
        run: |
          npm install
          vsce package
        working-directory: ./redmatch-lsp-client-vscode

      - name: upload .vsix to github tag
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{github.workspace}}/redmatch-lsp-client-vscode/redmatch*.vsix
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: upload .jar to github tag
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{github.workspace}}/redmatch-cli/target/redmatch-cli*.jar
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: publish plugin
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        run: npm run deploy
        working-directory: ./redmatch-lsp-client-vscode
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}